name = "All the Goons 1"
author = "Rouge"
version = "1.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "97ad9765a7ddd7c77f0d8a00f4d59e6fb6d26d5861c4b415adfe15d4c61fb96c"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.215"

[options]
acceptable-game-versions = ["1.21.1"]
