[Gameplay]
	dropsMoney = true
	autoStackGelsColor = true
	returnPotionGlassBottle = false
	rightClickRideMinecart = true
	# Default: 128
	# Range: > 0
	announcementBoxDistance = 128
	alertPlayerDungeon = false
	starPhase = false
	ammoSlotsBlacklist = ["confluence:falling_star", "#c:seeds"]
	terraStyleExplosion = true

[Recipe]
	fletchingMenu = true
	shimmerDecompose = true
	altarTips = true

[Spawning]
	doMeteoriteSpawning = true

	[Spawning."Falling Star"]
		doFallingStarSpawning = true
		# Default: 2400
		# Range: 20 ~ 20000
		fallingStarInterval = 2400

	[Spawning.NPC]
		doNPCSpawning = true
		# Default: 2400
		# Range: 20 ~ 20000
		npcSpawnInterval = 2400
		broadcastNpcMsg = true

[PlayerDeath]
	showMoneyDrops = true
	dropsTombstone = true
	# Default: 3
	# Range: > 0
	defaultRespawnTimeMin = 3
	# Default: 8
	# Range: > 0
	defaultRespawnTimeMax = 8
	# Default: 9
	# Range: > 0
	bossRespawnTimeMin = 9
	# Default: 18
	# Range: > 0
	bossRespawnTimeMax = 18

[WorldGeneration]
	wrappedCrimsonHeart = false
	instantlyHardmodeConversion = false

	[Compatibility.ArsNouveau]
		convertArsNouveauMana = false

	[Compatibility.IronsSpell]
		convertIronsSpellMana = false

	[Compatibility.FTB]
		ftbChunksWormholePotion = true

	[Compatibility.Xaero]
		xaerosMapWormholePotion = true
		xaerosMapPylonWaypoint = true

	[Compatibility.Waystones]
		waystonesPylonNonCost = true
