#Enable tracking pointer
Available = true
#Scale of cursor
# Default: 0.6
# Range: 0.01 ~ 4.0
Scale = 0.6
#Max tracking quantity
# Default: 10
# Range: 1 ~ 400
"Max quantity" = 10
#Interval between world position refresh
# Default: 1
# Range: 1 ~ 160
Interval = 1
#Enable center relative icon display
"Center relative available" = true
#The algorithm of center rela projection
#Allowed Values: MERCATOR, AITOFF, WINKEL_TRIPLE
"Project algorithm" = "AITOFF"
#Enable full track icon display
"Track full available" = false
#Enable longitude icon display
"Head flat available" = true
#List of entity types with cursors for center relative display, separated with "|"
"EntityType|PointerIconType|EntityIconType(|OptionalValue)" = ["minecraft:ender_dragon|normal_red|ender_dragon_head", "minecraft:wither|normal_white|wither_head", "terra_entity:king_slime|normal_red|king_slime", "terra_entity:eye_of_cthulhu|normal_red|eye_of_cthulhu", "terra_entity:brain_of_cthulhu|normal_red|brain_of_cthulhu", "terra_entity:eater_of_worlds|normal_red|eater_of_worlds", "terra_entity:queen_bee|normal_red|queen_bee", "terra_entity:skeletron|normal_red|skeletron", "terra_entity:demon_eye|normal_red|none", "terra_entity:flying_fish|normal_red|none", "terra_entity:crimera|normal_red|none", "terra_entity:eater_of_souls|normal_red|none", "terra_entity:giant_worm|normal_red|none", "terra_entity:tomb_crawler|normal_red|none", "terra_entity:devourer|normal_red|none", "terra_entity:cave_bat|normal_red|none", "terra_entity:jungle_bat|normal_red|none", "terra_entity:snatcher|normal_red|none", "terra_entity:man_eater|normal_red|none", "terra_entity:hornet|normal_red|none", "terra_entity:hell_bat|normal_red|none", "terra_entity:ice_bat|normal_red|none", "terra_entity:spore_bat|normal_red|none", "terra_entity:harpy|normal_red|none", "terra_entity:cursed_skull|normal_red|none", "terra_entity:dark_caster|normal_red|none", "terra_entity:antlion_swarmer|normal_red|none", "terra_entity:giant_antlion_swarmer|normal_red|none", "terra_entity:wyvern|normal_red|none", "terra_entity:granite_elemental|normal_red|none", "terra_entity:ghost|normal_red|none", "terra_entity:fire_imp|normal_red|none", "terra_entity:demon|normal_red|none", "terra_entity:voodoo_demon|normal_red|none"]
#List of entity types with cursors for full track display, separated with "|"
"entityType|type:icon(|optionalPattern)" = ["minecraft:wither|normal:point_x"]
