#In order for the block to be found by the Metal Detector
#You need to fill the list with string like 'modid:block[state1=true]' or 'modid:block'
#The higher the block in the list, the higher the value
rareBlocks = ["confluence:chlorophyte_ore", "confluence:deepslate_titanium_ore", "confluence:deepslate_adamantite_ore", "confluence:deepslate_orichalcum_ore", "confluence:deepslate_mythril_ore", "confluence:deepslate_palladium_ore", "confluence:deepslate_cobalt_ore", "confluence:life_crystal_block", "confluence:sword_in_stone", "confluence:dungeon_chest", "confluence:water_chest", "confluence:frozen_chest", "confluence:sandstone_chest", "confluence:golden_chest", "confluence:shadow_chest", "confluence:skyware_chest", "confluence:living_wood_chest", "confluence:opal_ore", "confluence:gelstone_ore", "confluence:cold_crystal_ore", "confluence:crimtane_ore", "confluence:deepslate_crimtane_ore", "confluence:demonite_ore", "confluence:deepslate_demonite_ore", "minecraft:ancient_debris", "minecraft:diamond_ore", "minecraft:deepslate_diamond_ore", "confluence:platinum_ore", "confluence:deepslate_platinum_ore", "minecraft:gold_ore", "minecraft:deepslate_gold_ore", "confluence:forest_pot", "confluence:tundra_pot", "confluence:spider_nest_pot", "confluence:underground_desert_pot", "confluence:jungle_pot", "confluence:marble_cave_pot", "confluence:pyramid_pot", "confluence:corruption_pot", "confluence:crimson_pot", "confluence:dungeon_pot", "confluence:underworld_pot", "confluence:lihzahrd_pot", "confluence:tungsten_ore", "confluence:deepslate_tungsten_ore", "confluence:silver_ore", "confluence:deepslate_silver_ore", "confluence:lead_ore", "confluence:deepslate_lead_ore", "minecraft:iron_ore", "minecraft:deepslate_iron_ore", "confluence:tin_ore", "confluence:deepslate_tin_ore", "minecraft:copper_ore", "minecraft:deepslate_copper_ore"]
#In order for the creature to be found by the Life Form Analyzer
#You need to fill the list with string like 'modid:entity'
#The higher the creature in the list, the higher the value
rareCreatures = ["terra_entity:dungeon_slime", "terra_entity:nymph", "terra_entity:wandering_eye_fish", "terra_entity:golden_slime", "terra_entity:pink_slime", "minecraft:skeleton_horse", "minecraft:sniffer", "minecraft:allay", "minecraft:warden", "minecraft:mooshroom", "minecraft:panda"]
# Default: 7
# Range: 6 ~ 100
"Max Accessory Amount" = 7

["Random Attack Damage"]
	enable = false
	# Default: 0.8
	# Range: 0.0 ~ 1.0
	min = 0.8
	# Default: 1.2
	# Range: 1.0 ~ 2.0
	max = 1.2
